/* Paper Garden style: the contact block is a practical school-office page pinned into the editorial flow, with calm pending details and a map framed like a noticeboard sheet. */
import { useState } from "react";
import { Mail, MapPin, Phone, Clock3 } from "lucide-react";
import { MapView } from "@/components/Map";

export function ContactMapSection() {
  const [mapReady, setMapReady] = useState(false);
  return <section className="contact-section" id="contact"><div className="contact-section__inner"><div className="contact-copy"><div className="field-label"><span className="field-mark field-mark--clay" /> Find the school office</div><h2>Come by,<br /><em>say hello.</em></h2><p>Our office details are being prepared for publication. Please check back soon for the school’s confirmed address, contact lines, and visiting hours.</p><div className="contact-details"><div className="contact-detail"><MapPin size={18} /><div><span className="eyebrow">Address</span><strong>School address coming soon</strong><small>Official location details will be published here.</small></div></div><div className="contact-detail"><Phone size={18} /><div><span className="eyebrow">Phone</span><strong>School office line coming soon</strong><small>Our confirmed phone number will be added here.</small></div></div><div className="contact-detail"><Mail size={18} /><div><span className="eyebrow">Email</span><strong>School email coming soon</strong><small>Families will find the official inbox here.</small></div></div><div className="contact-detail"><Clock3 size={18} /><div><span className="eyebrow">Office hours</span><strong>Visiting hours coming soon</strong><small>Confirmed office hours will be shared here.</small></div></div></div></div><div className="contact-map-wrap"><div className="contact-map__label"><span className="field-mark field-mark--green" /> School location</div><div className="contact-map-stage"><MapView className="contact-map" initialCenter={{ lat: 14.5995, lng: 120.9842 }} initialZoom={12} onMapReady={() => setMapReady(true)} />{!mapReady && <div className="contact-map-fallback"><MapPin size={28} /><strong>Map location coming soon</strong><span>The official school pin will appear here once details are confirmed.</span></div>}</div><div className="contact-map__caption">A clear meeting point for families, teachers, and the wider school community.</div></div></div></section>;
}
