/* Paper Garden style: the full post view is a larger pinned sheet that gives one announcement room to breathe without losing the noticeboard’s useful metadata. */
import { useState } from "react";
import { ArrowUpRight, Download, MapPin, Paperclip, Pin, X } from "lucide-react";
import type { SchoolPost } from "@/lib/firebase";
import { sanitizePostHtml } from "@/lib/sanitize";

export function PostDetail({ post, onClose }: { post: SchoolPost; onClose: () => void }) {
  const [preview, setPreview] = useState<NonNullable<SchoolPost["attachments"]>[number] | null>(null);
  const attachments = post.attachments || [];
  const canPreview = (attachment: NonNullable<SchoolPost["attachments"]>[number]) => attachment.type.startsWith("image/") || attachment.type === "application/pdf" || attachment.name.toLowerCase().endsWith(".pdf");
  return <div className="detail-overlay" role="dialog" aria-modal="true" aria-label={post.title} onClick={onClose}><article className="detail-sheet" onClick={(event) => event.stopPropagation()}><button type="button" className="detail-close icon-button" onClick={onClose} aria-label="Close post details"><X size={19} /></button><div className="detail-sheet__top"><span className={`detail-kind ${post.kind === "activity" ? "is-activity" : ""}`}>{post.kind === "activity" ? "Activity" : "Announcement"}</span><span className="detail-date">{post.dateLabel}</span></div><h1>{post.title}</h1><div className="detail-sheet__meta"><span>{post.gradeLevel}</span><span>{post.subject}</span>{post.location && <span><MapPin size={14} /> {post.location}</span>}</div><div className="detail-sheet__body rich-content" dangerouslySetInnerHTML={{ __html: sanitizePostHtml(post.body) }} />{attachments.length > 0 && <div className="detail-files"><div className="eyebrow">Attached for families</div>{attachments.map((attachment) => <button type="button" className="detail-file" key={attachment.url} onClick={() => canPreview(attachment) ? setPreview(attachment) : window.open(attachment.url, "_blank", "noopener,noreferrer")}><Paperclip size={16} /><span>{attachment.name}</span><strong>{canPreview(attachment) ? "Preview" : "Download"}</strong></button>)}</div>}<div className="detail-sheet__footer"><span><Pin size={14} /> Posted by {post.authorName}</span><button type="button" className="text-link" onClick={onClose}>Back to the board <ArrowUpRight size={15} /></button></div></article>{preview && <div className="detail-preview" role="dialog" aria-modal="true" aria-label={`Preview ${preview.name}`} onClick={() => setPreview(null)}><div className="detail-preview__card" onClick={(event) => event.stopPropagation()}><div className="detail-preview__head"><strong>{preview.name}</strong><button type="button" className="icon-button" onClick={() => setPreview(null)} aria-label="Close file preview"><X size={17} /></button></div><div className="detail-preview__body">{preview.type.startsWith("image/") ? <img src={preview.url} alt={preview.name} /> : <iframe src={`${preview.url}#toolbar=1`} title={`Preview of ${preview.name}`} />}</div><div className="detail-preview__foot"><span>Open or save this school file.</span><a className="button button--ink" href={preview.url} target="_blank" rel="noreferrer"><Download size={15} /> Download</a></div></div></div>}</div>;
}
